### ISSUE TITLE
EF Specific Conditions Gen1 parsing/definition wrong

### ISSUE THREAD

**Issue by jinzo** [kyburz-switzerland-ag/tachoparser#1]
Hi,

first I would like to thank you for open sourcing this, I have been researching this space (on and off) for quite some time. I don't have experience with Go, so my understanding of the code is limited. This bug report also has a dual function - I'm wondering if you are prepared to develop this software further "out in the open"? Are you prepared to accept contributions? Is this actually used somewhere in production?

I did a quick look and some tests and found a bug with EF Specific Conditions Gen1 - you have defined `ConditionPointerNewestRecord` field for the EF Specific Conditions Gen1 here:  https://github.com/kyburz-switzerland-ag/tachoparser/blob/83b9e660ca8e2e1e5b5bb50b6247b97d4c819783/pkg/decoder/definitions.go#L3007-L3011

But this is only present in Gen2 of EF Specific Conditions and therefore the Gen1 parsing does not work correctly.
Reference in the docs: TCS_154 for GEN2 and TCS_150 for GEN1 - attached pictures as I don't know how to link to this directly:
![Screenshot from 2024-04-13 15-39-16](https://github.com/kyburz-switzerland-ag/tachoparser/assets/858821/d465a39e-57c9-45f3-be31-724ddfcd9013)
![Screenshot from 2024-04-13 15-50-38](https://github.com/kyburz-switzerland-ag/tachoparser/assets/858821/e28ea95d-ed44-4546-9561-9ff04755aeae)

Thank you again!

**Comment by tcriess** [comment]
Hi, sorry for taking so long, I have not been notified about this issue...
I'm on holiday at the moment, but I'll certainly have a look when I am back in two weeks.

**Comment by jinzo** [comment]
No problem, I wish you happy and relaxing holidays! 
Let's talk when you are back, I'm interested in cooperation and have at least some experience with this (also some PII free sample files and some other resources).

**Comment by tcriess** [comment]
Hi, indeed, the 1st gen card contains a fixed number of specific conditions records (56), probably I mixed that up with the 2nd gen definition (or one of the many other confusing definitions. Should be fixed now.

**Comment by jinzo** [comment]
Yeah, it's a dense document with a lot of info to sift thorough, so I fully understand you :)

Thank you for fixing this, I will probably invest some more time into testing this soon-ish and report what I find.
