### ISSUE TITLE
Support for Europen DDD, C1B and C1C files ?

### ISSUE THREAD

**Issue by crouti** [kyburz-switzerland-ag/tachoparser#2]
Hello,

Thank you very much for your fantastic work!
I am trying to analyze of file of mine (ddd) that seems to raise an error. I can send it to you privately if needed.

Is your app supporting C1B and C1C file formats ?

thank you very much

**Comment by jinzo** [comment]
From a quick overview I did C1B is French specific and this software only handles EU Specified files (see: [docs/](https://github.com/kyburz-switzerland-ag/tachoparser/tree/83b9e660ca8e2e1e5b5bb50b6247b97d4c819783/docs) ). Not sure about the compatibility, as I never encountered French specific files yet - but would not count on it.

But unfortunately it seems that @kyburz-switzerland-ag / @tcriess are not active here. As I found some bug(s) too, and did not get any response. I still did not decide if I continue with my project or try to fork this one (as this has crypto verification done, which is not trivial to do, but I'm not comfortable with Go).

**Comment by tcriess** [comment]
I will certainly continue working on this, and happy to accept contributions, as the implementation of this specification turned out to be quite a challenge (translating 100s of pages of a PDF document into code...). As for the specific French files, I am not familiar with those, only the EU norm is implemented so far.

**Comment by crouti** [comment]
Would you accept a mission to update this code in order to be compatible with the latest EU spécification ? if yes, please accept my relation demand on LinkedIn. Thank you very mucj-h

**Comment by tcriess** [comment]
Hi - sure! I'll close this issue for now, we can exchange about this personally.
